//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int carId { get; set; }
        public string carCompany { get; set; }
        public string model { get; set; }
        public int numSeats { get; set; }
        public bool trunc { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
        public int owner { get; set; }
        public int insuranceType { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string file { get; set; }
        public string carNum { get; set; }
    
        public virtual User User { get; set; }
        public virtual Insurance Insurance { get; set; }
    }
}
