//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int demanedId { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.TimeSpan> fromHour { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<System.TimeSpan> toHour { get; set; }
        public Nullable<double> Locationx { get; set; }
        public Nullable<double> Locationy { get; set; }
        public Nullable<int> interestedId { get; set; }
        public Nullable<int> numSeats { get; set; }
        public string carCompany { get; set; }
        public Nullable<bool> isDone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
