//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public Nullable<int> demandId { get; set; }
        public Nullable<int> supplyId { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.TimeSpan> beginHour { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.TimeSpan> endHour { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
